# Generated by Django 4.1.3 on 2022-12-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=30, unique=True, verbose_name="Slug Name"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description Text"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="images.image",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Name")),
                (
                    "sub_title",
                    models.CharField(max_length=25, verbose_name="Sub Title"),
                ),
                ("link", models.URLField(verbose_name="Url to Host in whmcs")),
                ("price", models.IntegerField(verbose_name="Price (Toman)")),
                (
                    "sub_price",
                    models.CharField(max_length=40, verbose_name="Sub Price"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("iran", "ایران"), ("europe", "اروپا")],
                        max_length=15,
                        verbose_name="Location",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="images.image",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
    ]
