# Generated by Django 4.1.3 on 2022-12-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_title"),
        ("hosts", "0003_host_trending"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="Detail"),
                ),
                ("slashed", models.BooleanField(default=False, verbose_name="Slashed")),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="images.image",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="host",
            name="specs",
            field=models.ManyToManyField(to="hosts.hostspecs", verbose_name="Specs"),
        ),
    ]
