# Generated by Django 4.1.3 on 2022-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0004_hostspecs_host_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostspecs",
            name="typ",
            field=models.CharField(
                choices=[("main", "اصلی"), ("sub", "جزعی")],
                default="main",
                max_length=10,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
