# Generated by Django 4.1.3 on 2022-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0005_hostspecs_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcategory",
            name="badge",
            field=models.CharField(
                choices=[("new", "جدید"), ("soon", "بزودی"), ("none", "بدون بج")],
                default="none",
                max_length=10,
                verbose_name="Badge",
            ),
        ),
    ]
