# Generated by Django 4.1.3 on 2022-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0006_hostcategory_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcategory",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="DIsabled"),
        ),
    ]
