# Generated by Django 4.1.3 on 2022-12-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_title"),
        ("hosts", "0007_hostcategory_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcategory",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="host_categories_icon",
                to="images.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="hostcategory",
            name="short_text",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Short Description"
            ),
        ),
    ]
