# Generated by Django 4.1.3 on 2022-12-03 12:00

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Title")),
                (
                    "image",
                    models.ImageField(
                        upload_to=images.models.image_image_path, verbose_name="Image"
                    ),
                ),
            ],
        ),
    ]
